// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DfReader is a Reader for the Df structure.
type DfReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DfReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDfOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewDfInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDfOK creates a DfOK with default headers values
func NewDfOK() *DfOK {
	return &DfOK{}
}

/* DfOK describes a response with status code 200, with default header values.

Disk usage
*/
type DfOK struct {
	Payload *DfOKBody
}

func (o *DfOK) Error() string {
	return fmt.Sprintf("[GET /libpod/system/df][%d] dfOK  %+v", 200, o.Payload)
}
func (o *DfOK) GetPayload() *DfOKBody {
	return o.Payload
}

func (o *DfOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DfOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDfInternalServerError creates a DfInternalServerError with default headers values
func NewDfInternalServerError() *DfInternalServerError {
	return &DfInternalServerError{}
}

/* DfInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type DfInternalServerError struct {
	Payload *DfInternalServerErrorBody
}

func (o *DfInternalServerError) Error() string {
	return fmt.Sprintf("[GET /libpod/system/df][%d] dfInternalServerError  %+v", 500, o.Payload)
}
func (o *DfInternalServerError) GetPayload() *DfInternalServerErrorBody {
	return o.Payload
}

func (o *DfInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DfInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*DfInternalServerErrorBody df internal server error body
swagger:model DfInternalServerErrorBody
*/
type DfInternalServerErrorBody struct {

	// API root cause formatted for automated parsing
	// Example: API root cause
	Because string `json:"cause,omitempty"`

	// human error message, formatted for a human to read
	// Example: human error message
	Message string `json:"message,omitempty"`

	// http response code
	ResponseCode int64 `json:"response,omitempty"`
}

// Validate validates this df internal server error body
func (o *DfInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this df internal server error body based on context it is used
func (o *DfInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DfInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DfInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res DfInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DfOKBody df o k body
swagger:model DfOKBody
*/
type DfOKBody struct {

	// containers
	Containers []*DfOKBodyContainersItems0 `json:"Containers"`

	// images
	Images []*DfOKBodyImagesItems0 `json:"Images"`

	// volumes
	Volumes []*DfOKBodyVolumesItems0 `json:"Volumes"`
}

// Validate validates this df o k body
func (o *DfOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateContainers(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateImages(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateVolumes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DfOKBody) validateContainers(formats strfmt.Registry) error {
	if swag.IsZero(o.Containers) { // not required
		return nil
	}

	for i := 0; i < len(o.Containers); i++ {
		if swag.IsZero(o.Containers[i]) { // not required
			continue
		}

		if o.Containers[i] != nil {
			if err := o.Containers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("dfOK" + "." + "Containers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *DfOKBody) validateImages(formats strfmt.Registry) error {
	if swag.IsZero(o.Images) { // not required
		return nil
	}

	for i := 0; i < len(o.Images); i++ {
		if swag.IsZero(o.Images[i]) { // not required
			continue
		}

		if o.Images[i] != nil {
			if err := o.Images[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("dfOK" + "." + "Images" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *DfOKBody) validateVolumes(formats strfmt.Registry) error {
	if swag.IsZero(o.Volumes) { // not required
		return nil
	}

	for i := 0; i < len(o.Volumes); i++ {
		if swag.IsZero(o.Volumes[i]) { // not required
			continue
		}

		if o.Volumes[i] != nil {
			if err := o.Volumes[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("dfOK" + "." + "Volumes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this df o k body based on the context it is used
func (o *DfOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateContainers(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateImages(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateVolumes(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DfOKBody) contextValidateContainers(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Containers); i++ {

		if o.Containers[i] != nil {
			if err := o.Containers[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("dfOK" + "." + "Containers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *DfOKBody) contextValidateImages(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Images); i++ {

		if o.Images[i] != nil {
			if err := o.Images[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("dfOK" + "." + "Images" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *DfOKBody) contextValidateVolumes(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Volumes); i++ {

		if o.Volumes[i] != nil {
			if err := o.Volumes[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("dfOK" + "." + "Volumes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *DfOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DfOKBody) UnmarshalBinary(b []byte) error {
	var res DfOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DfOKBodyContainersItems0 SystemDfContainerReport describes a container for use with df
swagger:model DfOKBodyContainersItems0
*/
type DfOKBodyContainersItems0 struct {

	// command
	Command []string `json:"Command"`

	// container ID
	ContainerID string `json:"ContainerID,omitempty"`

	// created
	// Format: date-time
	Created strfmt.DateTime `json:"Created,omitempty"`

	// image
	Image string `json:"Image,omitempty"`

	// local volumes
	LocalVolumes int64 `json:"LocalVolumes,omitempty"`

	// names
	Names string `json:"Names,omitempty"`

	// r w size
	RWSize int64 `json:"RWSize,omitempty"`

	// size
	Size int64 `json:"Size,omitempty"`

	// status
	Status string `json:"Status,omitempty"`
}

// Validate validates this df o k body containers items0
func (o *DfOKBodyContainersItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCreated(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DfOKBodyContainersItems0) validateCreated(formats strfmt.Registry) error {
	if swag.IsZero(o.Created) { // not required
		return nil
	}

	if err := validate.FormatOf("Created", "body", "date-time", o.Created.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this df o k body containers items0 based on context it is used
func (o *DfOKBodyContainersItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DfOKBodyContainersItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DfOKBodyContainersItems0) UnmarshalBinary(b []byte) error {
	var res DfOKBodyContainersItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DfOKBodyImagesItems0 SystemDfImageReport describes an image for use with df
swagger:model DfOKBodyImagesItems0
*/
type DfOKBodyImagesItems0 struct {

	// containers
	Containers int64 `json:"Containers,omitempty"`

	// created
	// Format: date-time
	Created strfmt.DateTime `json:"Created,omitempty"`

	// image ID
	ImageID string `json:"ImageID,omitempty"`

	// repository
	Repository string `json:"Repository,omitempty"`

	// shared size
	SharedSize int64 `json:"SharedSize,omitempty"`

	// size
	Size int64 `json:"Size,omitempty"`

	// tag
	Tag string `json:"Tag,omitempty"`

	// unique size
	UniqueSize int64 `json:"UniqueSize,omitempty"`
}

// Validate validates this df o k body images items0
func (o *DfOKBodyImagesItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCreated(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DfOKBodyImagesItems0) validateCreated(formats strfmt.Registry) error {
	if swag.IsZero(o.Created) { // not required
		return nil
	}

	if err := validate.FormatOf("Created", "body", "date-time", o.Created.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this df o k body images items0 based on context it is used
func (o *DfOKBodyImagesItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DfOKBodyImagesItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DfOKBodyImagesItems0) UnmarshalBinary(b []byte) error {
	var res DfOKBodyImagesItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DfOKBodyVolumesItems0 SystemDfVolumeReport describes a volume and its size
swagger:model DfOKBodyVolumesItems0
*/
type DfOKBodyVolumesItems0 struct {

	// links
	Links int64 `json:"Links,omitempty"`

	// size
	Size int64 `json:"Size,omitempty"`

	// volume name
	VolumeName string `json:"VolumeName,omitempty"`
}

// Validate validates this df o k body volumes items0
func (o *DfOKBodyVolumesItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this df o k body volumes items0 based on context it is used
func (o *DfOKBodyVolumesItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DfOKBodyVolumesItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DfOKBodyVolumesItems0) UnmarshalBinary(b []byte) error {
	var res DfOKBodyVolumesItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
