// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PruneSystemReader is a Reader for the PruneSystem structure.
type PruneSystemReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PruneSystemReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPruneSystemOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPruneSystemBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPruneSystemInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPruneSystemOK creates a PruneSystemOK with default headers values
func NewPruneSystemOK() *PruneSystemOK {
	return &PruneSystemOK{}
}

/*PruneSystemOK handles this case with default header values.

Prune report
*/
type PruneSystemOK struct {
	Payload *PruneSystemOKBody
}

func (o *PruneSystemOK) Error() string {
	return fmt.Sprintf("[POST /libpod/system/prune][%d] pruneSystemOK  %+v", 200, o.Payload)
}

func (o *PruneSystemOK) GetPayload() *PruneSystemOKBody {
	return o.Payload
}

func (o *PruneSystemOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PruneSystemOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPruneSystemBadRequest creates a PruneSystemBadRequest with default headers values
func NewPruneSystemBadRequest() *PruneSystemBadRequest {
	return &PruneSystemBadRequest{}
}

/*PruneSystemBadRequest handles this case with default header values.

Bad parameter in request
*/
type PruneSystemBadRequest struct {
	Payload *PruneSystemBadRequestBody
}

func (o *PruneSystemBadRequest) Error() string {
	return fmt.Sprintf("[POST /libpod/system/prune][%d] pruneSystemBadRequest  %+v", 400, o.Payload)
}

func (o *PruneSystemBadRequest) GetPayload() *PruneSystemBadRequestBody {
	return o.Payload
}

func (o *PruneSystemBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PruneSystemBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPruneSystemInternalServerError creates a PruneSystemInternalServerError with default headers values
func NewPruneSystemInternalServerError() *PruneSystemInternalServerError {
	return &PruneSystemInternalServerError{}
}

/*PruneSystemInternalServerError handles this case with default header values.

Internal server error
*/
type PruneSystemInternalServerError struct {
	Payload *PruneSystemInternalServerErrorBody
}

func (o *PruneSystemInternalServerError) Error() string {
	return fmt.Sprintf("[POST /libpod/system/prune][%d] pruneSystemInternalServerError  %+v", 500, o.Payload)
}

func (o *PruneSystemInternalServerError) GetPayload() *PruneSystemInternalServerErrorBody {
	return o.Payload
}

func (o *PruneSystemInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PruneSystemInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PruneSystemBadRequestBody prune system bad request body
swagger:model PruneSystemBadRequestBody
*/
type PruneSystemBadRequestBody struct {

	// API root cause formatted for automated parsing
	Because string `json:"cause,omitempty"`

	// human error message, formatted for a human to read
	Message string `json:"message,omitempty"`

	// http response code
	ResponseCode int64 `json:"response,omitempty"`
}

// Validate validates this prune system bad request body
func (o *PruneSystemBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PruneSystemBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PruneSystemBadRequestBody) UnmarshalBinary(b []byte) error {
	var res PruneSystemBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PruneSystemInternalServerErrorBody prune system internal server error body
swagger:model PruneSystemInternalServerErrorBody
*/
type PruneSystemInternalServerErrorBody struct {

	// API root cause formatted for automated parsing
	Because string `json:"cause,omitempty"`

	// human error message, formatted for a human to read
	Message string `json:"message,omitempty"`

	// http response code
	ResponseCode int64 `json:"response,omitempty"`
}

// Validate validates this prune system internal server error body
func (o *PruneSystemInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PruneSystemInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PruneSystemInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res PruneSystemInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PruneSystemOKBody prune system o k body
swagger:model PruneSystemOKBody
*/
type PruneSystemOKBody struct {

	// err
	Err map[string]string `json:"Err,omitempty"`

	// ID
	ID map[string]int64 `json:"ID,omitempty"`

	// pod prune report
	PodPruneReport []*PruneSystemOKBodyPodPruneReportItems0 `json:"PodPruneReport"`

	// report
	Report *PruneSystemOKBodyReport `json:"Report,omitempty"`

	// size
	Size int64 `json:"Size,omitempty"`

	// volume prune report
	VolumePruneReport []*PruneSystemOKBodyVolumePruneReportItems0 `json:"VolumePruneReport"`
}

// Validate validates this prune system o k body
func (o *PruneSystemOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validatePodPruneReport(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateReport(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateVolumePruneReport(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PruneSystemOKBody) validatePodPruneReport(formats strfmt.Registry) error {

	if swag.IsZero(o.PodPruneReport) { // not required
		return nil
	}

	for i := 0; i < len(o.PodPruneReport); i++ {
		if swag.IsZero(o.PodPruneReport[i]) { // not required
			continue
		}

		if o.PodPruneReport[i] != nil {
			if err := o.PodPruneReport[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("pruneSystemOK" + "." + "PodPruneReport" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *PruneSystemOKBody) validateReport(formats strfmt.Registry) error {

	if swag.IsZero(o.Report) { // not required
		return nil
	}

	if o.Report != nil {
		if err := o.Report.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pruneSystemOK" + "." + "Report")
			}
			return err
		}
	}

	return nil
}

func (o *PruneSystemOKBody) validateVolumePruneReport(formats strfmt.Registry) error {

	if swag.IsZero(o.VolumePruneReport) { // not required
		return nil
	}

	for i := 0; i < len(o.VolumePruneReport); i++ {
		if swag.IsZero(o.VolumePruneReport[i]) { // not required
			continue
		}

		if o.VolumePruneReport[i] != nil {
			if err := o.VolumePruneReport[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("pruneSystemOK" + "." + "VolumePruneReport" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *PruneSystemOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PruneSystemOKBody) UnmarshalBinary(b []byte) error {
	var res PruneSystemOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PruneSystemOKBodyPodPruneReportItems0 prune system o k body pod prune report items0
swagger:model PruneSystemOKBodyPodPruneReportItems0
*/
type PruneSystemOKBodyPodPruneReportItems0 struct {

	// err
	Err string `json:"Err,omitempty"`

	// Id
	ID string `json:"Id,omitempty"`
}

// Validate validates this prune system o k body pod prune report items0
func (o *PruneSystemOKBodyPodPruneReportItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PruneSystemOKBodyPodPruneReportItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PruneSystemOKBodyPodPruneReportItems0) UnmarshalBinary(b []byte) error {
	var res PruneSystemOKBodyPodPruneReportItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PruneSystemOKBodyReport prune system o k body report
swagger:model PruneSystemOKBodyReport
*/
type PruneSystemOKBodyReport struct {

	// err
	Err map[string]string `json:"Err,omitempty"`

	// Id
	ID []string `json:"Id"`
}

// Validate validates this prune system o k body report
func (o *PruneSystemOKBodyReport) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PruneSystemOKBodyReport) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PruneSystemOKBodyReport) UnmarshalBinary(b []byte) error {
	var res PruneSystemOKBodyReport
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PruneSystemOKBodyVolumePruneReportItems0 prune system o k body volume prune report items0
swagger:model PruneSystemOKBodyVolumePruneReportItems0
*/
type PruneSystemOKBodyVolumePruneReportItems0 struct {

	// err
	Err string `json:"Err,omitempty"`

	// Id
	ID string `json:"Id,omitempty"`
}

// Validate validates this prune system o k body volume prune report items0
func (o *PruneSystemOKBodyVolumePruneReportItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PruneSystemOKBodyVolumePruneReportItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PruneSystemOKBodyVolumePruneReportItems0) UnmarshalBinary(b []byte) error {
	var res PruneSystemOKBodyVolumePruneReportItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
