// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SystemVersionReader is a Reader for the SystemVersion structure.
type SystemVersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SystemVersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSystemVersionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSystemVersionOK creates a SystemVersionOK with default headers values
func NewSystemVersionOK() *SystemVersionOK {
	return &SystemVersionOK{}
}

/*SystemVersionOK handles this case with default header values.

Version
*/
type SystemVersionOK struct {
	Payload *SystemVersionOKBody
}

func (o *SystemVersionOK) Error() string {
	return fmt.Sprintf("[GET /libpod/version][%d] systemVersionOK  %+v", 200, o.Payload)
}

func (o *SystemVersionOK) GetPayload() *SystemVersionOKBody {
	return o.Payload
}

func (o *SystemVersionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(SystemVersionOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*SystemVersionOKBody system version o k body
swagger:model SystemVersionOKBody
*/
type SystemVersionOKBody struct {

	// client
	Client *SystemVersionOKBodyClient `json:"Client,omitempty"`

	// server
	Server *SystemVersionOKBodyServer `json:"Server,omitempty"`
}

// Validate validates this system version o k body
func (o *SystemVersionOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateClient(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateServer(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SystemVersionOKBody) validateClient(formats strfmt.Registry) error {

	if swag.IsZero(o.Client) { // not required
		return nil
	}

	if o.Client != nil {
		if err := o.Client.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("systemVersionOK" + "." + "Client")
			}
			return err
		}
	}

	return nil
}

func (o *SystemVersionOKBody) validateServer(formats strfmt.Registry) error {

	if swag.IsZero(o.Server) { // not required
		return nil
	}

	if o.Server != nil {
		if err := o.Server.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("systemVersionOK" + "." + "Server")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *SystemVersionOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SystemVersionOKBody) UnmarshalBinary(b []byte) error {
	var res SystemVersionOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*SystemVersionOKBodyClient Version is an output struct for varlink
swagger:model SystemVersionOKBodyClient
*/
type SystemVersionOKBodyClient struct {

	// API version
	APIVersion int64 `json:"APIVersion,omitempty"`

	// built
	Built int64 `json:"Built,omitempty"`

	// built time
	BuiltTime string `json:"BuiltTime,omitempty"`

	// git commit
	GitCommit string `json:"GitCommit,omitempty"`

	// go version
	GoVersion string `json:"GoVersion,omitempty"`

	// os arch
	OsArch string `json:"OsArch,omitempty"`

	// version
	Version string `json:"Version,omitempty"`
}

// Validate validates this system version o k body client
func (o *SystemVersionOKBodyClient) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *SystemVersionOKBodyClient) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SystemVersionOKBodyClient) UnmarshalBinary(b []byte) error {
	var res SystemVersionOKBodyClient
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*SystemVersionOKBodyServer Version is an output struct for varlink
swagger:model SystemVersionOKBodyServer
*/
type SystemVersionOKBodyServer struct {

	// API version
	APIVersion int64 `json:"APIVersion,omitempty"`

	// built
	Built int64 `json:"Built,omitempty"`

	// built time
	BuiltTime string `json:"BuiltTime,omitempty"`

	// git commit
	GitCommit string `json:"GitCommit,omitempty"`

	// go version
	GoVersion string `json:"GoVersion,omitempty"`

	// os arch
	OsArch string `json:"OsArch,omitempty"`

	// version
	Version string `json:"Version,omitempty"`
}

// Validate validates this system version o k body server
func (o *SystemVersionOKBodyServer) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *SystemVersionOKBodyServer) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SystemVersionOKBodyServer) UnmarshalBinary(b []byte) error {
	var res SystemVersionOKBodyServer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
