// Code generated by go-swagger; DO NOT EDIT.

package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LibpodImagesRemoveReader is a Reader for the LibpodImagesRemove structure.
type LibpodImagesRemoveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LibpodImagesRemoveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLibpodImagesRemoveOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewLibpodImagesRemoveBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewLibpodImagesRemoveInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewLibpodImagesRemoveOK creates a LibpodImagesRemoveOK with default headers values
func NewLibpodImagesRemoveOK() *LibpodImagesRemoveOK {
	return &LibpodImagesRemoveOK{}
}

/* LibpodImagesRemoveOK describes a response with status code 200, with default header values.

Remove response
*/
type LibpodImagesRemoveOK struct {
	Payload *LibpodImagesRemoveOKBody
}

func (o *LibpodImagesRemoveOK) Error() string {
	return fmt.Sprintf("[DELETE /libpod/images/remove][%d] libpodImagesRemoveOK  %+v", 200, o.Payload)
}
func (o *LibpodImagesRemoveOK) GetPayload() *LibpodImagesRemoveOKBody {
	return o.Payload
}

func (o *LibpodImagesRemoveOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(LibpodImagesRemoveOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLibpodImagesRemoveBadRequest creates a LibpodImagesRemoveBadRequest with default headers values
func NewLibpodImagesRemoveBadRequest() *LibpodImagesRemoveBadRequest {
	return &LibpodImagesRemoveBadRequest{}
}

/* LibpodImagesRemoveBadRequest describes a response with status code 400, with default header values.

Bad parameter in request
*/
type LibpodImagesRemoveBadRequest struct {
	Payload *LibpodImagesRemoveBadRequestBody
}

func (o *LibpodImagesRemoveBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /libpod/images/remove][%d] libpodImagesRemoveBadRequest  %+v", 400, o.Payload)
}
func (o *LibpodImagesRemoveBadRequest) GetPayload() *LibpodImagesRemoveBadRequestBody {
	return o.Payload
}

func (o *LibpodImagesRemoveBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(LibpodImagesRemoveBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLibpodImagesRemoveInternalServerError creates a LibpodImagesRemoveInternalServerError with default headers values
func NewLibpodImagesRemoveInternalServerError() *LibpodImagesRemoveInternalServerError {
	return &LibpodImagesRemoveInternalServerError{}
}

/* LibpodImagesRemoveInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type LibpodImagesRemoveInternalServerError struct {
	Payload *LibpodImagesRemoveInternalServerErrorBody
}

func (o *LibpodImagesRemoveInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /libpod/images/remove][%d] libpodImagesRemoveInternalServerError  %+v", 500, o.Payload)
}
func (o *LibpodImagesRemoveInternalServerError) GetPayload() *LibpodImagesRemoveInternalServerErrorBody {
	return o.Payload
}

func (o *LibpodImagesRemoveInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(LibpodImagesRemoveInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*LibpodImagesRemoveBadRequestBody libpod images remove bad request body
swagger:model LibpodImagesRemoveBadRequestBody
*/
type LibpodImagesRemoveBadRequestBody struct {

	// API root cause formatted for automated parsing
	// Example: API root cause
	Because string `json:"cause,omitempty"`

	// human error message, formatted for a human to read
	// Example: human error message
	Message string `json:"message,omitempty"`

	// http response code
	ResponseCode int64 `json:"response,omitempty"`
}

// Validate validates this libpod images remove bad request body
func (o *LibpodImagesRemoveBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this libpod images remove bad request body based on context it is used
func (o *LibpodImagesRemoveBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *LibpodImagesRemoveBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *LibpodImagesRemoveBadRequestBody) UnmarshalBinary(b []byte) error {
	var res LibpodImagesRemoveBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*LibpodImagesRemoveInternalServerErrorBody libpod images remove internal server error body
swagger:model LibpodImagesRemoveInternalServerErrorBody
*/
type LibpodImagesRemoveInternalServerErrorBody struct {

	// API root cause formatted for automated parsing
	// Example: API root cause
	Because string `json:"cause,omitempty"`

	// human error message, formatted for a human to read
	// Example: human error message
	Message string `json:"message,omitempty"`

	// http response code
	ResponseCode int64 `json:"response,omitempty"`
}

// Validate validates this libpod images remove internal server error body
func (o *LibpodImagesRemoveInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this libpod images remove internal server error body based on context it is used
func (o *LibpodImagesRemoveInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *LibpodImagesRemoveInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *LibpodImagesRemoveInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res LibpodImagesRemoveInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*LibpodImagesRemoveOKBody LibpodImagesRemoveReport is the return type for image removal via the rest
// api.
swagger:model LibpodImagesRemoveOKBody
*/
type LibpodImagesRemoveOKBody struct {

	// Deleted images.
	Deleted []string `json:"Deleted"`

	// Image removal requires is to return data and an error.
	Errors []string `json:"Errors"`

	// ExitCode describes the exit codes as described in the `podman rmi`
	// man page.
	ExitCode int64 `json:"ExitCode,omitempty"`

	// Untagged images. Can be longer than Deleted.
	Untagged []string `json:"Untagged"`
}

// Validate validates this libpod images remove o k body
func (o *LibpodImagesRemoveOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this libpod images remove o k body based on context it is used
func (o *LibpodImagesRemoveOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *LibpodImagesRemoveOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *LibpodImagesRemoveOKBody) UnmarshalBinary(b []byte) error {
	var res LibpodImagesRemoveOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
