// Code generated by go-swagger; DO NOT EDIT.

package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LibpodImagesLoadReader is a Reader for the LibpodImagesLoad structure.
type LibpodImagesLoadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LibpodImagesLoadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLibpodImagesLoadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewLibpodImagesLoadBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewLibpodImagesLoadInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewLibpodImagesLoadOK creates a LibpodImagesLoadOK with default headers values
func NewLibpodImagesLoadOK() *LibpodImagesLoadOK {
	return &LibpodImagesLoadOK{}
}

/* LibpodImagesLoadOK describes a response with status code 200, with default header values.

Load response
*/
type LibpodImagesLoadOK struct {
	Payload *LibpodImagesLoadOKBody
}

func (o *LibpodImagesLoadOK) Error() string {
	return fmt.Sprintf("[POST /libpod/images/load][%d] libpodImagesLoadOK  %+v", 200, o.Payload)
}
func (o *LibpodImagesLoadOK) GetPayload() *LibpodImagesLoadOKBody {
	return o.Payload
}

func (o *LibpodImagesLoadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(LibpodImagesLoadOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLibpodImagesLoadBadRequest creates a LibpodImagesLoadBadRequest with default headers values
func NewLibpodImagesLoadBadRequest() *LibpodImagesLoadBadRequest {
	return &LibpodImagesLoadBadRequest{}
}

/* LibpodImagesLoadBadRequest describes a response with status code 400, with default header values.

Bad parameter in request
*/
type LibpodImagesLoadBadRequest struct {
	Payload *LibpodImagesLoadBadRequestBody
}

func (o *LibpodImagesLoadBadRequest) Error() string {
	return fmt.Sprintf("[POST /libpod/images/load][%d] libpodImagesLoadBadRequest  %+v", 400, o.Payload)
}
func (o *LibpodImagesLoadBadRequest) GetPayload() *LibpodImagesLoadBadRequestBody {
	return o.Payload
}

func (o *LibpodImagesLoadBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(LibpodImagesLoadBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLibpodImagesLoadInternalServerError creates a LibpodImagesLoadInternalServerError with default headers values
func NewLibpodImagesLoadInternalServerError() *LibpodImagesLoadInternalServerError {
	return &LibpodImagesLoadInternalServerError{}
}

/* LibpodImagesLoadInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type LibpodImagesLoadInternalServerError struct {
	Payload *LibpodImagesLoadInternalServerErrorBody
}

func (o *LibpodImagesLoadInternalServerError) Error() string {
	return fmt.Sprintf("[POST /libpod/images/load][%d] libpodImagesLoadInternalServerError  %+v", 500, o.Payload)
}
func (o *LibpodImagesLoadInternalServerError) GetPayload() *LibpodImagesLoadInternalServerErrorBody {
	return o.Payload
}

func (o *LibpodImagesLoadInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(LibpodImagesLoadInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*LibpodImagesLoadBadRequestBody libpod images load bad request body
swagger:model LibpodImagesLoadBadRequestBody
*/
type LibpodImagesLoadBadRequestBody struct {

	// API root cause formatted for automated parsing
	// Example: API root cause
	Because string `json:"cause,omitempty"`

	// human error message, formatted for a human to read
	// Example: human error message
	Message string `json:"message,omitempty"`

	// http response code
	ResponseCode int64 `json:"response,omitempty"`
}

// Validate validates this libpod images load bad request body
func (o *LibpodImagesLoadBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this libpod images load bad request body based on context it is used
func (o *LibpodImagesLoadBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *LibpodImagesLoadBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *LibpodImagesLoadBadRequestBody) UnmarshalBinary(b []byte) error {
	var res LibpodImagesLoadBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*LibpodImagesLoadInternalServerErrorBody libpod images load internal server error body
swagger:model LibpodImagesLoadInternalServerErrorBody
*/
type LibpodImagesLoadInternalServerErrorBody struct {

	// API root cause formatted for automated parsing
	// Example: API root cause
	Because string `json:"cause,omitempty"`

	// human error message, formatted for a human to read
	// Example: human error message
	Message string `json:"message,omitempty"`

	// http response code
	ResponseCode int64 `json:"response,omitempty"`
}

// Validate validates this libpod images load internal server error body
func (o *LibpodImagesLoadInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this libpod images load internal server error body based on context it is used
func (o *LibpodImagesLoadInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *LibpodImagesLoadInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *LibpodImagesLoadInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res LibpodImagesLoadInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*LibpodImagesLoadOKBody libpod images load o k body
swagger:model LibpodImagesLoadOKBody
*/
type LibpodImagesLoadOKBody struct {

	// names
	Names []string `json:"Names"`
}

// Validate validates this libpod images load o k body
func (o *LibpodImagesLoadOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this libpod images load o k body based on context it is used
func (o *LibpodImagesLoadOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *LibpodImagesLoadOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *LibpodImagesLoadOKBody) UnmarshalBinary(b []byte) error {
	var res LibpodImagesLoadOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
