// Code generated by go-swagger; DO NOT EDIT.

package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LibpodPruneImagesReader is a Reader for the LibpodPruneImages structure.
type LibpodPruneImagesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LibpodPruneImagesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLibpodPruneImagesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewLibpodPruneImagesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewLibpodPruneImagesOK creates a LibpodPruneImagesOK with default headers values
func NewLibpodPruneImagesOK() *LibpodPruneImagesOK {
	return &LibpodPruneImagesOK{}
}

/* LibpodPruneImagesOK describes a response with status code 200, with default header values.

Delete response
*/
type LibpodPruneImagesOK struct {
	Payload []*LibpodPruneImagesOKBodyItems0
}

func (o *LibpodPruneImagesOK) Error() string {
	return fmt.Sprintf("[POST /libpod/images/prune][%d] libpodPruneImagesOK  %+v", 200, o.Payload)
}
func (o *LibpodPruneImagesOK) GetPayload() []*LibpodPruneImagesOKBodyItems0 {
	return o.Payload
}

func (o *LibpodPruneImagesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLibpodPruneImagesInternalServerError creates a LibpodPruneImagesInternalServerError with default headers values
func NewLibpodPruneImagesInternalServerError() *LibpodPruneImagesInternalServerError {
	return &LibpodPruneImagesInternalServerError{}
}

/* LibpodPruneImagesInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type LibpodPruneImagesInternalServerError struct {
	Payload *LibpodPruneImagesInternalServerErrorBody
}

func (o *LibpodPruneImagesInternalServerError) Error() string {
	return fmt.Sprintf("[POST /libpod/images/prune][%d] libpodPruneImagesInternalServerError  %+v", 500, o.Payload)
}
func (o *LibpodPruneImagesInternalServerError) GetPayload() *LibpodPruneImagesInternalServerErrorBody {
	return o.Payload
}

func (o *LibpodPruneImagesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(LibpodPruneImagesInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*LibpodPruneImagesInternalServerErrorBody libpod prune images internal server error body
swagger:model LibpodPruneImagesInternalServerErrorBody
*/
type LibpodPruneImagesInternalServerErrorBody struct {

	// API root cause formatted for automated parsing
	// Example: API root cause
	Because string `json:"cause,omitempty"`

	// human error message, formatted for a human to read
	// Example: human error message
	Message string `json:"message,omitempty"`

	// http response code
	ResponseCode int64 `json:"response,omitempty"`
}

// Validate validates this libpod prune images internal server error body
func (o *LibpodPruneImagesInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this libpod prune images internal server error body based on context it is used
func (o *LibpodPruneImagesInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *LibpodPruneImagesInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *LibpodPruneImagesInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res LibpodPruneImagesInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*LibpodPruneImagesOKBodyItems0 ImageDeleteResponse is the response for removing an image from storage and containers
// what was untagged vs actually removed
swagger:model LibpodPruneImagesOKBodyItems0
*/
type LibpodPruneImagesOKBodyItems0 struct {

	// deleted
	Deleted string `json:"deleted,omitempty"`

	// untagged
	Untagged []string `json:"untagged"`
}

// Validate validates this libpod prune images o k body items0
func (o *LibpodPruneImagesOKBodyItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this libpod prune images o k body items0 based on context it is used
func (o *LibpodPruneImagesOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *LibpodPruneImagesOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *LibpodPruneImagesOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res LibpodPruneImagesOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
