// Code generated by go-swagger; DO NOT EDIT.

package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewLibpodExportImageParams creates a new LibpodExportImageParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewLibpodExportImageParams() *LibpodExportImageParams {
	return &LibpodExportImageParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewLibpodExportImageParamsWithTimeout creates a new LibpodExportImageParams object
// with the ability to set a timeout on a request.
func NewLibpodExportImageParamsWithTimeout(timeout time.Duration) *LibpodExportImageParams {
	return &LibpodExportImageParams{
		timeout: timeout,
	}
}

// NewLibpodExportImageParamsWithContext creates a new LibpodExportImageParams object
// with the ability to set a context for a request.
func NewLibpodExportImageParamsWithContext(ctx context.Context) *LibpodExportImageParams {
	return &LibpodExportImageParams{
		Context: ctx,
	}
}

// NewLibpodExportImageParamsWithHTTPClient creates a new LibpodExportImageParams object
// with the ability to set a custom HTTPClient for a request.
func NewLibpodExportImageParamsWithHTTPClient(client *http.Client) *LibpodExportImageParams {
	return &LibpodExportImageParams{
		HTTPClient: client,
	}
}

/* LibpodExportImageParams contains all the parameters to send to the API endpoint
   for the libpod export image operation.

   Typically these are written to a http.Request.
*/
type LibpodExportImageParams struct {

	/* Compress.

	   use compression on image
	*/
	Compress *bool

	/* Format.

	   format for exported image
	*/
	Format *string

	/* Name.

	   the name or ID of the container
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the libpod export image params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LibpodExportImageParams) WithDefaults() *LibpodExportImageParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the libpod export image params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LibpodExportImageParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the libpod export image params
func (o *LibpodExportImageParams) WithTimeout(timeout time.Duration) *LibpodExportImageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the libpod export image params
func (o *LibpodExportImageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the libpod export image params
func (o *LibpodExportImageParams) WithContext(ctx context.Context) *LibpodExportImageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the libpod export image params
func (o *LibpodExportImageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the libpod export image params
func (o *LibpodExportImageParams) WithHTTPClient(client *http.Client) *LibpodExportImageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the libpod export image params
func (o *LibpodExportImageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCompress adds the compress to the libpod export image params
func (o *LibpodExportImageParams) WithCompress(compress *bool) *LibpodExportImageParams {
	o.SetCompress(compress)
	return o
}

// SetCompress adds the compress to the libpod export image params
func (o *LibpodExportImageParams) SetCompress(compress *bool) {
	o.Compress = compress
}

// WithFormat adds the format to the libpod export image params
func (o *LibpodExportImageParams) WithFormat(format *string) *LibpodExportImageParams {
	o.SetFormat(format)
	return o
}

// SetFormat adds the format to the libpod export image params
func (o *LibpodExportImageParams) SetFormat(format *string) {
	o.Format = format
}

// WithName adds the name to the libpod export image params
func (o *LibpodExportImageParams) WithName(name string) *LibpodExportImageParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the libpod export image params
func (o *LibpodExportImageParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *LibpodExportImageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Compress != nil {

		// query param compress
		var qrCompress bool

		if o.Compress != nil {
			qrCompress = *o.Compress
		}
		qCompress := swag.FormatBool(qrCompress)
		if qCompress != "" {

			if err := r.SetQueryParam("compress", qCompress); err != nil {
				return err
			}
		}
	}

	if o.Format != nil {

		// query param format
		var qrFormat string

		if o.Format != nil {
			qrFormat = *o.Format
		}
		qFormat := qrFormat
		if qFormat != "" {

			if err := r.SetQueryParam("format", qFormat); err != nil {
				return err
			}
		}
	}

	// path param name:.*
	if err := r.SetPathParam("name:.*", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
