// Code generated by go-swagger; DO NOT EDIT.

package containers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewChangesContainerParams creates a new ChangesContainerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewChangesContainerParams() *ChangesContainerParams {
	return &ChangesContainerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewChangesContainerParamsWithTimeout creates a new ChangesContainerParams object
// with the ability to set a timeout on a request.
func NewChangesContainerParamsWithTimeout(timeout time.Duration) *ChangesContainerParams {
	return &ChangesContainerParams{
		timeout: timeout,
	}
}

// NewChangesContainerParamsWithContext creates a new ChangesContainerParams object
// with the ability to set a context for a request.
func NewChangesContainerParamsWithContext(ctx context.Context) *ChangesContainerParams {
	return &ChangesContainerParams{
		Context: ctx,
	}
}

// NewChangesContainerParamsWithHTTPClient creates a new ChangesContainerParams object
// with the ability to set a custom HTTPClient for a request.
func NewChangesContainerParamsWithHTTPClient(client *http.Client) *ChangesContainerParams {
	return &ChangesContainerParams{
		HTTPClient: client,
	}
}

/* ChangesContainerParams contains all the parameters to send to the API endpoint
   for the changes container operation.

   Typically these are written to a http.Request.
*/
type ChangesContainerParams struct {

	/* Name.

	   the name or id of the container
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the changes container params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ChangesContainerParams) WithDefaults() *ChangesContainerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the changes container params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ChangesContainerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the changes container params
func (o *ChangesContainerParams) WithTimeout(timeout time.Duration) *ChangesContainerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the changes container params
func (o *ChangesContainerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the changes container params
func (o *ChangesContainerParams) WithContext(ctx context.Context) *ChangesContainerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the changes container params
func (o *ChangesContainerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the changes container params
func (o *ChangesContainerParams) WithHTTPClient(client *http.Client) *ChangesContainerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the changes container params
func (o *ChangesContainerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the changes container params
func (o *ChangesContainerParams) WithName(name string) *ChangesContainerParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the changes container params
func (o *ChangesContainerParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *ChangesContainerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
