// Code generated by go-swagger; DO NOT EDIT.

package containers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewLibpodRestartContainerParams creates a new LibpodRestartContainerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewLibpodRestartContainerParams() *LibpodRestartContainerParams {
	return &LibpodRestartContainerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewLibpodRestartContainerParamsWithTimeout creates a new LibpodRestartContainerParams object
// with the ability to set a timeout on a request.
func NewLibpodRestartContainerParamsWithTimeout(timeout time.Duration) *LibpodRestartContainerParams {
	return &LibpodRestartContainerParams{
		timeout: timeout,
	}
}

// NewLibpodRestartContainerParamsWithContext creates a new LibpodRestartContainerParams object
// with the ability to set a context for a request.
func NewLibpodRestartContainerParamsWithContext(ctx context.Context) *LibpodRestartContainerParams {
	return &LibpodRestartContainerParams{
		Context: ctx,
	}
}

// NewLibpodRestartContainerParamsWithHTTPClient creates a new LibpodRestartContainerParams object
// with the ability to set a custom HTTPClient for a request.
func NewLibpodRestartContainerParamsWithHTTPClient(client *http.Client) *LibpodRestartContainerParams {
	return &LibpodRestartContainerParams{
		HTTPClient: client,
	}
}

/* LibpodRestartContainerParams contains all the parameters to send to the API endpoint
   for the libpod restart container operation.

   Typically these are written to a http.Request.
*/
type LibpodRestartContainerParams struct {

	/* Name.

	   the name or ID of the container
	*/
	Name string

	/* T.

	   timeout before sending kill signal to container
	*/
	T *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the libpod restart container params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LibpodRestartContainerParams) WithDefaults() *LibpodRestartContainerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the libpod restart container params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LibpodRestartContainerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the libpod restart container params
func (o *LibpodRestartContainerParams) WithTimeout(timeout time.Duration) *LibpodRestartContainerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the libpod restart container params
func (o *LibpodRestartContainerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the libpod restart container params
func (o *LibpodRestartContainerParams) WithContext(ctx context.Context) *LibpodRestartContainerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the libpod restart container params
func (o *LibpodRestartContainerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the libpod restart container params
func (o *LibpodRestartContainerParams) WithHTTPClient(client *http.Client) *LibpodRestartContainerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the libpod restart container params
func (o *LibpodRestartContainerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the libpod restart container params
func (o *LibpodRestartContainerParams) WithName(name string) *LibpodRestartContainerParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the libpod restart container params
func (o *LibpodRestartContainerParams) SetName(name string) {
	o.Name = name
}

// WithT adds the t to the libpod restart container params
func (o *LibpodRestartContainerParams) WithT(t *int64) *LibpodRestartContainerParams {
	o.SetT(t)
	return o
}

// SetT adds the t to the libpod restart container params
func (o *LibpodRestartContainerParams) SetT(t *int64) {
	o.T = t
}

// WriteToRequest writes these params to a swagger request
func (o *LibpodRestartContainerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if o.T != nil {

		// query param t
		var qrT int64

		if o.T != nil {
			qrT = *o.T
		}
		qT := swag.FormatInt64(qrT)
		if qT != "" {

			if err := r.SetQueryParam("t", qT); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
