// Code generated by go-swagger; DO NOT EDIT.

package containers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewLibpodExportContainerParams creates a new LibpodExportContainerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewLibpodExportContainerParams() *LibpodExportContainerParams {
	return &LibpodExportContainerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewLibpodExportContainerParamsWithTimeout creates a new LibpodExportContainerParams object
// with the ability to set a timeout on a request.
func NewLibpodExportContainerParamsWithTimeout(timeout time.Duration) *LibpodExportContainerParams {
	return &LibpodExportContainerParams{
		timeout: timeout,
	}
}

// NewLibpodExportContainerParamsWithContext creates a new LibpodExportContainerParams object
// with the ability to set a context for a request.
func NewLibpodExportContainerParamsWithContext(ctx context.Context) *LibpodExportContainerParams {
	return &LibpodExportContainerParams{
		Context: ctx,
	}
}

// NewLibpodExportContainerParamsWithHTTPClient creates a new LibpodExportContainerParams object
// with the ability to set a custom HTTPClient for a request.
func NewLibpodExportContainerParamsWithHTTPClient(client *http.Client) *LibpodExportContainerParams {
	return &LibpodExportContainerParams{
		HTTPClient: client,
	}
}

/* LibpodExportContainerParams contains all the parameters to send to the API endpoint
   for the libpod export container operation.

   Typically these are written to a http.Request.
*/
type LibpodExportContainerParams struct {

	/* Name.

	   the name or ID of the container
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the libpod export container params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LibpodExportContainerParams) WithDefaults() *LibpodExportContainerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the libpod export container params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LibpodExportContainerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the libpod export container params
func (o *LibpodExportContainerParams) WithTimeout(timeout time.Duration) *LibpodExportContainerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the libpod export container params
func (o *LibpodExportContainerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the libpod export container params
func (o *LibpodExportContainerParams) WithContext(ctx context.Context) *LibpodExportContainerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the libpod export container params
func (o *LibpodExportContainerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the libpod export container params
func (o *LibpodExportContainerParams) WithHTTPClient(client *http.Client) *LibpodExportContainerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the libpod export container params
func (o *LibpodExportContainerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the libpod export container params
func (o *LibpodExportContainerParams) WithName(name string) *LibpodExportContainerParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the libpod export container params
func (o *LibpodExportContainerParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *LibpodExportContainerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
