// Code generated by go-swagger; DO NOT EDIT.

package containers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LibpodPauseContainerReader is a Reader for the LibpodPauseContainer structure.
type LibpodPauseContainerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LibpodPauseContainerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewLibpodPauseContainerNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewLibpodPauseContainerNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewLibpodPauseContainerInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewLibpodPauseContainerNoContent creates a LibpodPauseContainerNoContent with default headers values
func NewLibpodPauseContainerNoContent() *LibpodPauseContainerNoContent {
	return &LibpodPauseContainerNoContent{}
}

/* LibpodPauseContainerNoContent describes a response with status code 204, with default header values.

no error
*/
type LibpodPauseContainerNoContent struct {
}

func (o *LibpodPauseContainerNoContent) Error() string {
	return fmt.Sprintf("[POST /libpod/containers/{name}/pause][%d] libpodPauseContainerNoContent ", 204)
}

func (o *LibpodPauseContainerNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewLibpodPauseContainerNotFound creates a LibpodPauseContainerNotFound with default headers values
func NewLibpodPauseContainerNotFound() *LibpodPauseContainerNotFound {
	return &LibpodPauseContainerNotFound{}
}

/* LibpodPauseContainerNotFound describes a response with status code 404, with default header values.

No such container
*/
type LibpodPauseContainerNotFound struct {
	Payload *LibpodPauseContainerNotFoundBody
}

func (o *LibpodPauseContainerNotFound) Error() string {
	return fmt.Sprintf("[POST /libpod/containers/{name}/pause][%d] libpodPauseContainerNotFound  %+v", 404, o.Payload)
}
func (o *LibpodPauseContainerNotFound) GetPayload() *LibpodPauseContainerNotFoundBody {
	return o.Payload
}

func (o *LibpodPauseContainerNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(LibpodPauseContainerNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLibpodPauseContainerInternalServerError creates a LibpodPauseContainerInternalServerError with default headers values
func NewLibpodPauseContainerInternalServerError() *LibpodPauseContainerInternalServerError {
	return &LibpodPauseContainerInternalServerError{}
}

/* LibpodPauseContainerInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type LibpodPauseContainerInternalServerError struct {
	Payload *LibpodPauseContainerInternalServerErrorBody
}

func (o *LibpodPauseContainerInternalServerError) Error() string {
	return fmt.Sprintf("[POST /libpod/containers/{name}/pause][%d] libpodPauseContainerInternalServerError  %+v", 500, o.Payload)
}
func (o *LibpodPauseContainerInternalServerError) GetPayload() *LibpodPauseContainerInternalServerErrorBody {
	return o.Payload
}

func (o *LibpodPauseContainerInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(LibpodPauseContainerInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*LibpodPauseContainerInternalServerErrorBody libpod pause container internal server error body
swagger:model LibpodPauseContainerInternalServerErrorBody
*/
type LibpodPauseContainerInternalServerErrorBody struct {

	// API root cause formatted for automated parsing
	// Example: API root cause
	Because string `json:"cause,omitempty"`

	// human error message, formatted for a human to read
	// Example: human error message
	Message string `json:"message,omitempty"`

	// http response code
	ResponseCode int64 `json:"response,omitempty"`
}

// Validate validates this libpod pause container internal server error body
func (o *LibpodPauseContainerInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this libpod pause container internal server error body based on context it is used
func (o *LibpodPauseContainerInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *LibpodPauseContainerInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *LibpodPauseContainerInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res LibpodPauseContainerInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*LibpodPauseContainerNotFoundBody libpod pause container not found body
swagger:model LibpodPauseContainerNotFoundBody
*/
type LibpodPauseContainerNotFoundBody struct {

	// API root cause formatted for automated parsing
	// Example: API root cause
	Because string `json:"cause,omitempty"`

	// human error message, formatted for a human to read
	// Example: human error message
	Message string `json:"message,omitempty"`

	// http response code
	ResponseCode int64 `json:"response,omitempty"`
}

// Validate validates this libpod pause container not found body
func (o *LibpodPauseContainerNotFoundBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this libpod pause container not found body based on context it is used
func (o *LibpodPauseContainerNotFoundBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *LibpodPauseContainerNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *LibpodPauseContainerNotFoundBody) UnmarshalBinary(b []byte) error {
	var res LibpodPauseContainerNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
