// Code generated by go-swagger; DO NOT EDIT.

package containers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LibpodShowMountedContainersReader is a Reader for the LibpodShowMountedContainers structure.
type LibpodShowMountedContainersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LibpodShowMountedContainersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLibpodShowMountedContainersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewLibpodShowMountedContainersInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewLibpodShowMountedContainersOK creates a LibpodShowMountedContainersOK with default headers values
func NewLibpodShowMountedContainersOK() *LibpodShowMountedContainersOK {
	return &LibpodShowMountedContainersOK{}
}

/* LibpodShowMountedContainersOK describes a response with status code 200, with default header values.

mounted containers
*/
type LibpodShowMountedContainersOK struct {
	Payload map[string]string
}

func (o *LibpodShowMountedContainersOK) Error() string {
	return fmt.Sprintf("[GET /libpod/containers/showmounted][%d] libpodShowMountedContainersOK  %+v", 200, o.Payload)
}
func (o *LibpodShowMountedContainersOK) GetPayload() map[string]string {
	return o.Payload
}

func (o *LibpodShowMountedContainersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLibpodShowMountedContainersInternalServerError creates a LibpodShowMountedContainersInternalServerError with default headers values
func NewLibpodShowMountedContainersInternalServerError() *LibpodShowMountedContainersInternalServerError {
	return &LibpodShowMountedContainersInternalServerError{}
}

/* LibpodShowMountedContainersInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type LibpodShowMountedContainersInternalServerError struct {
	Payload *LibpodShowMountedContainersInternalServerErrorBody
}

func (o *LibpodShowMountedContainersInternalServerError) Error() string {
	return fmt.Sprintf("[GET /libpod/containers/showmounted][%d] libpodShowMountedContainersInternalServerError  %+v", 500, o.Payload)
}
func (o *LibpodShowMountedContainersInternalServerError) GetPayload() *LibpodShowMountedContainersInternalServerErrorBody {
	return o.Payload
}

func (o *LibpodShowMountedContainersInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(LibpodShowMountedContainersInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*LibpodShowMountedContainersInternalServerErrorBody libpod show mounted containers internal server error body
swagger:model LibpodShowMountedContainersInternalServerErrorBody
*/
type LibpodShowMountedContainersInternalServerErrorBody struct {

	// API root cause formatted for automated parsing
	// Example: API root cause
	Because string `json:"cause,omitempty"`

	// human error message, formatted for a human to read
	// Example: human error message
	Message string `json:"message,omitempty"`

	// http response code
	ResponseCode int64 `json:"response,omitempty"`
}

// Validate validates this libpod show mounted containers internal server error body
func (o *LibpodShowMountedContainersInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this libpod show mounted containers internal server error body based on context it is used
func (o *LibpodShowMountedContainersInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *LibpodShowMountedContainersInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *LibpodShowMountedContainersInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res LibpodShowMountedContainersInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
