// Code generated by go-swagger; DO NOT EDIT.

package containers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewLibpodStatsContainerParams creates a new LibpodStatsContainerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewLibpodStatsContainerParams() *LibpodStatsContainerParams {
	return &LibpodStatsContainerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewLibpodStatsContainerParamsWithTimeout creates a new LibpodStatsContainerParams object
// with the ability to set a timeout on a request.
func NewLibpodStatsContainerParamsWithTimeout(timeout time.Duration) *LibpodStatsContainerParams {
	return &LibpodStatsContainerParams{
		timeout: timeout,
	}
}

// NewLibpodStatsContainerParamsWithContext creates a new LibpodStatsContainerParams object
// with the ability to set a context for a request.
func NewLibpodStatsContainerParamsWithContext(ctx context.Context) *LibpodStatsContainerParams {
	return &LibpodStatsContainerParams{
		Context: ctx,
	}
}

// NewLibpodStatsContainerParamsWithHTTPClient creates a new LibpodStatsContainerParams object
// with the ability to set a custom HTTPClient for a request.
func NewLibpodStatsContainerParamsWithHTTPClient(client *http.Client) *LibpodStatsContainerParams {
	return &LibpodStatsContainerParams{
		HTTPClient: client,
	}
}

/* LibpodStatsContainerParams contains all the parameters to send to the API endpoint
   for the libpod stats container operation.

   Typically these are written to a http.Request.
*/
type LibpodStatsContainerParams struct {

	/* Name.

	   the name or ID of the container
	*/
	Name string

	/* Stream.

	   Stream the output

	   Default: true
	*/
	Stream *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the libpod stats container params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LibpodStatsContainerParams) WithDefaults() *LibpodStatsContainerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the libpod stats container params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LibpodStatsContainerParams) SetDefaults() {
	var (
		streamDefault = bool(true)
	)

	val := LibpodStatsContainerParams{
		Stream: &streamDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the libpod stats container params
func (o *LibpodStatsContainerParams) WithTimeout(timeout time.Duration) *LibpodStatsContainerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the libpod stats container params
func (o *LibpodStatsContainerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the libpod stats container params
func (o *LibpodStatsContainerParams) WithContext(ctx context.Context) *LibpodStatsContainerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the libpod stats container params
func (o *LibpodStatsContainerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the libpod stats container params
func (o *LibpodStatsContainerParams) WithHTTPClient(client *http.Client) *LibpodStatsContainerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the libpod stats container params
func (o *LibpodStatsContainerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the libpod stats container params
func (o *LibpodStatsContainerParams) WithName(name string) *LibpodStatsContainerParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the libpod stats container params
func (o *LibpodStatsContainerParams) SetName(name string) {
	o.Name = name
}

// WithStream adds the stream to the libpod stats container params
func (o *LibpodStatsContainerParams) WithStream(stream *bool) *LibpodStatsContainerParams {
	o.SetStream(stream)
	return o
}

// SetStream adds the stream to the libpod stats container params
func (o *LibpodStatsContainerParams) SetStream(stream *bool) {
	o.Stream = stream
}

// WriteToRequest writes these params to a swagger request
func (o *LibpodStatsContainerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if o.Stream != nil {

		// query param stream
		var qrStream bool

		if o.Stream != nil {
			qrStream = *o.Stream
		}
		qStream := swag.FormatBool(qrStream)
		if qStream != "" {

			if err := r.SetQueryParam("stream", qStream); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
